.TH "ControllingPointers" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ControllingPointers
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T > static void \fBcontrol\fP (const shared_ptr< T > &pointer, const string &className, const string &functionName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file ControllingPointers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
