.TH "logic::Observer" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Observer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBlogic::Score_L\fP, and \fBrepresentation::EntityView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Observer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
