.TH "logic::EntityModel" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::EntityModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::Subject\fP\&.
.PP
Inherited by \fBlogic::BG_Tile_L\fP, \fBlogic::Bonus_L\fP, \fBlogic::Platform_L\fP, and \fBlogic::Player_L\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprojectPointsToPixels\fP ()"
.br
.ti -1c
.RI "void \fBNotify\fP () override"
.br
.ti -1c
.RI "void \fBsetX\fP (float x)"
.br
.ti -1c
.RI "void \fBsetY\fP (float y)"
.br
.ti -1c
.RI "void \fBsetXprev\fP (float x)"
.br
.ti -1c
.RI "void \fBsetYprev\fP (float y)"
.br
.ti -1c
.RI "void \fBsetVelocityX\fP (float velocityX)"
.br
.ti -1c
.RI "void \fBsetVelocityY\fP (float velocityY)"
.br
.ti -1c
.RI "void \fBsetWidth\fP (float width)"
.br
.ti -1c
.RI "void \fBsetHeight\fP (float height)"
.br
.ti -1c
.RI "void \fBsetGravity\fP (float gravity)"
.br
.ti -1c
.RI "float \fBgetX\fP () const"
.br
.ti -1c
.RI "float \fBgetY\fP () const"
.br
.ti -1c
.RI "float \fBgetXprev\fP () const"
.br
.ti -1c
.RI "float \fBgetYprev\fP () const"
.br
.ti -1c
.RI "float \fBgetVelocityX\fP () const"
.br
.ti -1c
.RI "float \fBgetVelocityY\fP () const"
.br
.ti -1c
.RI "float \fBgetHeight\fP () const"
.br
.ti -1c
.RI "float \fBgetWidth\fP () const"
.br
.ti -1c
.RI "float \fBgetGravity\fP () const"
.br
.ti -1c
.RI "int \fBgetProjectedX\fP () const"
.br
.ti -1c
.RI "int \fBgetProjectedY\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file EntityModel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
