.TH "logic::Subject" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Subject
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBlogic::EntityModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddObserver\fP (const shared_ptr< \fBObserver\fP > &observer)"
.br
.ti -1c
.RI "void \fBremoveObserver\fP (const shared_ptr< \fBObserver\fP > &observer)"
.br
.ti -1c
.RI "virtual void \fBNotify\fP ()=0"
.br
.ti -1c
.RI "void \fBemptyObserver\fP ()"
.br
.ti -1c
.RI "vector< shared_ptr< \fBObserver\fP > > & \fBgetObservers\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Subject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
