.TH "logic::World" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::World
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetFactory\fP (shared_ptr< \fBEntityFactory\fP > &factory)"
.br
.ti -1c
.RI "void \fBsetupWorld\fP ()"
.br
.ti -1c
.RI "bool \fBgetGameStatus\fP ()"
.br
.ti -1c
.RI "void \fBupdateWorld\fP ()"
.br
.ti -1c
.RI "void \fBreleaseObservers\fP ()"
.br
.ti -1c
.RI "void \fBchangeGameStatus\fP ()"
.br
.ti -1c
.RI "void \fBsaveScore\fP ()"
.br
.ti -1c
.RI "int \fBgetScore\fP ()"
.br
.ti -1c
.RI "int \fBgetHighScore\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file World\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
