.TH "logic::Rocket_L" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Rocket_L
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::Bonus_L\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRocket_L\fP (float posX, float posY, float width, float height)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 123 of file Bonus\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
