.TH "logic::Bonus_L" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Bonus_L
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::EntityModel\fP\&.
.PP
Inherited by \fBlogic::Rocket_L\fP, and \fBlogic::Spring_L\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBonus_L\fP (float posX, float posY, float width, float height)"
.br
.ti -1c
.RI "float \fBgetForce\fP () const"
.br
.ti -1c
.RI "bool \fBgetInvolmsVelocity\fP () const"
.br
.ti -1c
.RI "void \fBsetIncreasingValue\fP (int value)"
.br
.ti -1c
.RI "int \fBgetIncreasingValue\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBm_bonusforce\fP {}"
.br
.ti -1c
.RI "bool \fBm_involmsVeloctiy\fP"
.br
.ti -1c
.RI "int \fBm_increasingValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Bonus\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
