.TH "logic::Platform_L_temporary" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic::Platform_L_temporary
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::Platform_L\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlatform_L_temporary\fP (float posX, float posY, float width, float height)"
.br
.ti -1c
.RI "void \fBmovePlatform\fP () override"
.br
.ti -1c
.RI "void \fBchangeDirection\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 254 of file Platform\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
