.TH "nullptrException" 3 "Fri Jan 14 2022" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nullptrException
.SH SYNOPSIS
.br
.PP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnullptrException\fP (string className, string functionName)"
.br
.ti -1c
.RI "string \fBwhat_\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file Exceptions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
