.TH "representation::ConcreteFactory" 3 "Wed Dec 22 2021" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::ConcreteFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogic::EntityFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreatePlayer\fP (shared_ptr< \fBlogic::Player_L\fP > &player) override"
.br
.ti -1c
.RI "void \fBcreateBG_Tile\fP (shared_ptr< \fBlogic::BG_Tile_L\fP > &bg_tile) override"
.br
.ti -1c
.RI "void \fBcreatePlatform\fP (shared_ptr< \fBlogic::Platform_L\fP > &platform, PlatformType type) override"
.br
.ti -1c
.RI "void \fBcreateBonus\fP (shared_ptr< \fBlogic::Bonus_L\fP > &bonus, BonusType type) override"
.br
.ti -1c
.RI "void \fBcreateScore\fP (shared_ptr< \fBlogic::Player_L\fP > &player, shared_ptr< \fBlogic::Score\fP > &score) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file ConcreteFactory\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
