.TH "representation::BG_Tile" 3 "Wed Dec 22 2021" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::BG_Tile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepresentation::EntityView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBG_Tile\fP (shared_ptr< \fBlogic::BG_Tile_L\fP > &BG_tile, string image)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file BG_Tile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
