.TH "representation::Game" 3 "Wed Dec 22 2021" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::Game
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdisplayFullGame\fP ()"
.br
.ti -1c
.RI "void \fBdisplayMenu\fP ()"
.br
.ti -1c
.RI "void \fBbeginGame\fP ()"
.br
.ti -1c
.RI "void \fBstopGame\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file Game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
