.TH "representation::Platform" 3 "Wed Dec 22 2021" "Doxygen Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
representation::Platform
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepresentation::EntityView\fP\&.
.PP
Inherited by \fBrepresentation::Platform_horizontal\fP, \fBrepresentation::Platform_static\fP, \fBrepresentation::Platform_temporary\fP, and \fBrepresentation::Platform_vertical\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlatform\fP (shared_ptr< \fBlogic::Platform_L\fP > &platform, string &image)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file Platform\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Test from the source code\&.
